repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: mixed-line-ending
      args: [--fix=crlf]
    - id: no-commit-to-branch
      args: [--branch, main, --branch, develop]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: [--settings, setup.cfg]

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.7.0
  hooks:
    - id: black
      exclude: (migrations)
      language_version: python3.11
      args: [--line-length=79, --skip-string-normalization]

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-docstrings
      args: [--config, setup.cfg]
