version: '3.3'
services:

  db:
    image: postgres:13.10-alpine
    restart: always
    ports:
      - "54321:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  pg_data:
